<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="5" hostname="WTC-5159473-l2" name="TestNG.MFAC_Changed_Before_Method" tests="17" failures="4" timestamp="12 Oct 2018 16:36:13 GMT" time="28.605" errors="0">
  <testcase name="IssuePin" time="0.214" classname="TestNG.MFAC_Changed_Before_Method"/>
  <testcase name="AddressVelocity" time="7.185" classname="TestNG.MFAC_Changed_Before_Method">
    <failure type="java.lang.AssertionError" message="
Expected: (a string containing &quot;DENY&quot; and a string containing &quot;Unfortunately, too many failed attempts for registration have occurred. Please try again later.&quot;)
     but: a string containing &quot;DENY&quot; was &quot;{&quot;transactionId&quot;:&quot;7db2568f-e935-4eec-b05b-89db28fa9891&quot;,&quot;output&quot;:{&quot;advice&quot;:&quot;ALLOW&quot;}}&quot;">
      <![CDATA[java.lang.AssertionError: 
Expected: (a string containing "DENY" and a string containing "Unfortunately, too many failed attempts for registration have occurred. Please try again later.")
     but: a string containing "DENY" was "{"transactionId":"7db2568f-e935-4eec-b05b-89db28fa9891","output":{"advice":"ALLOW"}}"
at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
at org.junit.Assert.assertThat(Assert.java:956)
at org.junit.Assert.assertThat(Assert.java:923)
at TestNG.MFAC_Changed_Before_Method.AddressVelocity(MFAC_Changed_Before_Method.java:197)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:71)
at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:14)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
]]>
    </failure>
  </testcase> <!-- AddressVelocity -->
  <testcase name="IssuePinVelocity" time="4.005" classname="TestNG.MFAC_Changed_Before_Method">
    <failure type="java.lang.AssertionError" message="
Expected: (a string containing &quot;5700&quot; and a string containing &quot;Unfortunately, you have exceeded your attempts for verification. Please try again later.&quot;)
     but: a string containing &quot;5700&quot; was &quot;{&quot;transactionId&quot;:&quot;1b83236b-2018-45ad-ba10-8d76b4c8797d&quot;,&quot;output&quot;:{&quot;pinOTP&quot;:&quot;565272&quot;,&quot;pinExpirationDate&quot;:&quot;10/12/2018 04:45 PM GMT&quot;}}&quot;">
      <![CDATA[java.lang.AssertionError: 
Expected: (a string containing "5700" and a string containing "Unfortunately, you have exceeded your attempts for verification. Please try again later.")
     but: a string containing "5700" was "{"transactionId":"1b83236b-2018-45ad-ba10-8d76b4c8797d","output":{"pinOTP":"565272","pinExpirationDate":"10/12/2018 04:45 PM GMT"}}"
at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
at org.junit.Assert.assertThat(Assert.java:956)
at org.junit.Assert.assertThat(Assert.java:923)
at TestNG.MFAC_Changed_Before_Method.IssuePinVelocity(MFAC_Changed_Before_Method.java:234)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:71)
at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:14)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
]]>
    </failure>
  </testcase> <!-- IssuePinVelocity -->
  <testcase name="IssuePin" time="0.428" classname="TestNG.MFAC_Changed_Before_Method"/>
  <testcase name="VerifyPinNoLongerValid" time="0.873" classname="TestNG.MFAC_Changed_Before_Method"/>
  <testcase name="VerifyPinValid" time="0.344" classname="TestNG.MFAC_Changed_Before_Method"/>
  <testcase name="VerifyPinValid" time="0.407" classname="TestNG.MFAC_Changed_Before_Method"/>
  <testcase name="VerifyPinVelocity" time="1.015" classname="TestNG.MFAC_Changed_Before_Method"/>
  <testcase name="AddressVelocity" time="8.247" classname="TestNG.MFAC_Changed_Before_Method">
    <failure type="java.lang.AssertionError" message="
Expected: (a string containing &quot;DENY&quot; and a string containing &quot;Unfortunately, too many failed attempts for registration have occurred. Please try again later.&quot;)
     but: a string containing &quot;DENY&quot; was &quot;{&quot;transactionId&quot;:&quot;3520c10f-6d09-4f12-8d06-85b6d2f7a7c1&quot;,&quot;output&quot;:{&quot;advice&quot;:&quot;ALLOW&quot;}}&quot;">
      <![CDATA[java.lang.AssertionError: 
Expected: (a string containing "DENY" and a string containing "Unfortunately, too many failed attempts for registration have occurred. Please try again later.")
     but: a string containing "DENY" was "{"transactionId":"3520c10f-6d09-4f12-8d06-85b6d2f7a7c1","output":{"advice":"ALLOW"}}"
at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
at org.junit.Assert.assertThat(Assert.java:956)
at org.junit.Assert.assertThat(Assert.java:923)
at TestNG.MFAC_Changed_Before_Method.AddressVelocity(MFAC_Changed_Before_Method.java:197)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:71)
at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:14)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
]]>
    </failure>
  </testcase> <!-- AddressVelocity -->
  <testcase name="VerifyPinNoLongerValid" time="0.807" classname="TestNG.MFAC_Changed_Before_Method"/>
  <testcase name="IssuePinVelocity" time="3.896" classname="TestNG.MFAC_Changed_Before_Method">
    <failure type="java.lang.AssertionError" message="
Expected: (a string containing &quot;5700&quot; and a string containing &quot;Unfortunately, you have exceeded your attempts for verification. Please try again later.&quot;)
     but: a string containing &quot;5700&quot; was &quot;{&quot;transactionId&quot;:&quot;229c82ee-f472-4c2f-8367-fe0e000241ff&quot;,&quot;output&quot;:{&quot;pinOTP&quot;:&quot;274346&quot;,&quot;pinExpirationDate&quot;:&quot;10/12/2018 05:05 PM GMT&quot;}}&quot;">
      <![CDATA[java.lang.AssertionError: 
Expected: (a string containing "5700" and a string containing "Unfortunately, you have exceeded your attempts for verification. Please try again later.")
     but: a string containing "5700" was "{"transactionId":"229c82ee-f472-4c2f-8367-fe0e000241ff","output":{"pinOTP":"274346","pinExpirationDate":"10/12/2018 05:05 PM GMT"}}"
at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
at org.junit.Assert.assertThat(Assert.java:956)
at org.junit.Assert.assertThat(Assert.java:923)
at TestNG.MFAC_Changed_Before_Method.IssuePinVelocity(MFAC_Changed_Before_Method.java:234)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:71)
at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:14)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
]]>
    </failure>
  </testcase> <!-- IssuePinVelocity -->
  <testcase name="VerifyPinVelocity" time="1.184" classname="TestNG.MFAC_Changed_Before_Method"/>
  <testcase name="AdditionalEnrollmentExpiration" classname="TestNG.MFAC_Changed_Before_Method">
    <skipped/>
  </testcase> <!-- AdditionalEnrollmentExpiration -->
  <testcase name="AdditionalEnrollmentExpirationValidate" classname="TestNG.MFAC_Changed_Before_Method">
    <skipped/>
  </testcase> <!-- AdditionalEnrollmentExpirationValidate -->
  <testcase name="IssuePinExpirationValidate" classname="TestNG.MFAC_Changed_Before_Method">
    <skipped/>
  </testcase> <!-- IssuePinExpirationValidate -->
  <testcase name="DetermineLockoutTime" classname="TestNG.MFAC_Changed_Before_Method">
    <skipped/>
  </testcase> <!-- DetermineLockoutTime -->
  <testcase name="IssuePinExpiration" classname="TestNG.MFAC_Changed_Before_Method">
    <skipped/>
  </testcase> <!-- IssuePinExpiration -->
</testsuite> <!-- TestNG.MFAC_Changed_Before_Method -->
